### ISSUE TITLE
Admin panel: error when saving config preferences

### ISSUE THREAD

**Issue by uniconstructor** [dreamfactorysoftware/dreamfactory#1]
1) Open admin console
2) Select "Config" section
3) Select "Preferences"
4) Change any checkbox and click "Update"

Request Details
Url: http://dreamfactory2.dev/api/v2/user/custom
Method: POST

Request body:
```json
{
    "adminPreferences": {
        "application": {
            "notificationSystem": {
                "success": "pnotify",
                "error": "pnotify",
                "warn": "pnotify"
            }
        },
        "data": {
            "app": {
                "include_count": true,
                "limit": 100,
                "related": "role_by_role_id"
            },
            "app_group": {
                "include_count": true,
                "limit": 100,
                "related": "app_to_app_group_by_group_id"
            },
            "role": {
                "include_count": true,
                "related": "role_service_access_by_role_id,role_lookup_by_role_id",
                "limit": 100
            },
            "admin": {
                "include_count": true,
                "limit": 20,
                "related": "user_lookup_by_user_id"
            },
            "user": {
                "include_count": true,
                "limit": 20,
                "related": "user_lookup_by_user_id,user_to_app_to_role_by_user_id"
            },
            "service": {
                "include_count": true,
                "include_components": true,
                "limit": 100,
                "related": "service_doc_by_service_id"
            },
            "config": {},
            "email_template": {},
            "lookup": {},
            "cors": {},
            "event": {
                "full_map": true
            }
        },
        "sections": {
            "app": {
                "autoClose": true,
                "manageViewMode": "table"
            },
            "role": {
                "autoClose": true,
                "manageViewMode": "table"
            },
            "admin": {
                "autoClose": true,
                "manageViewMode": "list"
            },
            "user": {
                "autoClose": true,
                "manageViewMode": "table"
            },
            "service": {
                "autoClose": true,
                "manageViewMode": "table"
            }
        }
    }
}
```

Full responce text:
```json
{
    "error": {
        "context": null,
        "message": "No record(s) detected in request.",
        "code": 400,
        "trace": ["|", "|", "|#0 /Users/frost/Sites/dreamfactory2.dev/vendor/dreamfactory/df-user/src/Resources/Custom.php(29):", "|----> DreamFactory\\Core\\Resources\\System\\BaseSystemResource->handlePOST()", "|", "|#1 [internal function]: DreamFactory\\Core\\User\\Resources\\Custom->handlePOST()", "|", "|#2 /Users/frost/Sites/dreamfactory2.dev/vendor/dreamfactory/df-core/src/Components/RestHandler.php(263):", "|----> call_user_func(Array)", "|", "|#3 /Users/frost/Sites/dreamfactory2.dev/vendor/dreamfactory/df-core/src/Components/RestHandler.php(169):", "|----> DreamFactory\\Core\\Components\\RestHandler->processRequest()", "|", "|#4 /Users/frost/Sites/dreamfactory2.dev/vendor/dreamfactory/df-core/src/Components/RestHandler.php(216):", "|----> DreamFactory\\Core\\Components\\RestHandler->handleRequest(Object(DreamFactory\\Core\\Utility\\ServiceRequest), '')", "|", "|#5 /Users/frost/Sites/dreamfactory2.dev/vendor/dreamfactory/df-core/src/Components/RestHandler.php(164):", "|----> DreamFactory\\Core\\Components\\RestHandler->handleResource(Array)", "|", "|#6 /Users/frost/Sites/dreamfactory2.dev/vendor/dreamfactory/df-core/src/Utility/ServiceHandler.php(68):", "|----> DreamFactory\\Core\\Components\\RestHandler->handleRequest(Object(DreamFactory\\Core\\Utility\\ServiceRequest), 'custom')", "|", "|#7 /Users/frost/Sites/dreamfactory2.dev/app/Http/Controllers/RestController.php(221):", "|----> DreamFactory\\Core\\Utility\\ServiceHandler::processRequest('v2', 'user', 'custom')", "|", "|#8 /Users/frost/Sites/dreamfactory2.dev/app/Http/Controllers/RestController.php(152):", "|----> DreamFactory\\Http\\Controllers\\RestController->handleService('v2', 'user', 'custom')", "|", "|#9 [internal function]: DreamFactory\\Http\\Controllers\\RestController->handlePOST('v2', 'user', 'custom')", "|", "|#10 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(8490):", "|----> call_user_func_array(Array, Array)", "|", "|#11 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(8559):", "|----> Illuminate\\Routing\\Controller->callAction('handlePOST', Array)", "|", "|#12 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(8539):", "|----> Illuminate\\Routing\\ControllerDispatcher->call(Object(DreamFactory\\Http\\Controllers\\RestController), Object(Illuminate\\Routing\\Route), 'handlePOST')", "|", "|#13 [internal function]: Illuminate\\Routing\\ControllerDispatcher->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#14 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9196):", "|----> call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))", "|", "|#15 /Users/frost/Sites/dreamfactory2.dev/app/Http/Middleware/Limits.php(111):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#16 [internal function]: Dreamfactory\\Http\\Middleware\\Limits->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#17 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#18 /Users/frost/Sites/dreamfactory2.dev/app/Http/Middleware/AccessCheck.php(232):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#19 [internal function]: DreamFactory\\Http\\Middleware\\AccessCheck->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#20 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#21 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#22 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9178):", "|----> call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))", "|", "|#23 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(8540):", "|----> Illuminate\\Pipeline\\Pipeline->then(Object(Closure))", "|", "|#24 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(8525):", "|----> Illuminate\\Routing\\ControllerDispatcher->callWithinStack(Object(DreamFactory\\Http\\Controllers\\RestController), Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'handlePOST')", "|", "|#25 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(7500):", "|----> Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'DreamFactory\\\\Ht...', 'handlePOST')", "|", "|#26 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(7471):", "|----> Illuminate\\Routing\\Route->runWithCustomDispatcher(Object(Illuminate\\Http\\Request))", "|", "|#27 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(7124):", "|----> Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))", "|", "|#28 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#29 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9196):", "|----> call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))", "|", "|#30 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#31 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9178):", "|----> call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))", "|", "|#32 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(7125):", "|----> Illuminate\\Pipeline\\Pipeline->then(Object(Closure))", "|", "|#33 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(7113):", "|----> Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))", "|", "|#34 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(7098):", "|----> Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))", "|", "|#35 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(2088):", "|----> Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))", "|", "|#36 [internal function]: Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#37 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9196):", "|----> call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))", "|", "|#38 /Users/frost/Sites/dreamfactory2.dev/vendor/barryvdh/laravel-cors/src/HandleCors.php(43):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#39 [internal function]: Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#40 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#41 /Users/frost/Sites/dreamfactory2.dev/app/Http/Middleware/FirstUserCheck.php(45):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#42 [internal function]: DreamFactory\\Http\\Middleware\\FirstUserCheck->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#43 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#44 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(12456):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#45 [internal function]: Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#46 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#47 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(11104):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#48 [internal function]: Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#49 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#50 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(12193):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#51 [internal function]: Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#52 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#53 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(12132):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#54 [internal function]: Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#55 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#56 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(2758):", "|----> Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#57 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))", "|", "|#58 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9188):", "|----> call_user_func_array(Array, Array)", "|", "|#59 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))", "|", "|#60 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(9178):", "|----> call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))", "|", "|#61 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(2035):", "|----> Illuminate\\Pipeline\\Pipeline->then(Object(Closure))", "|", "|#62 /Users/frost/Sites/dreamfactory2.dev/bootstrap/cache/compiled.php(2018):", "|----> Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))", "|", "|#63 /Users/frost/Sites/dreamfactory2.dev/public/index.php(53):", "|----> Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))", "|", "|#64 {main}"]
    }
}
```

**Comment by df-arif** [comment]
This is fixed now.
