### ISSUE TITLE
DF 2.2/2.2.1: Service definition as YAML doesnt work / Fatal error in API Docs

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#98]
When setting a swagger definition as YAML, the API Docs show an 500 error. Also the following is logged in dreamfactory.log

```
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Class 'Symfony\Component\Yaml\Yaml' not found in /opt/dreamfactory/vendor/dreamfactory/df-core/src/Models/Service.php:348
Stack trace:
#0 /opt/dreamfactory/vendor/dreamfactory/df-core/src/Models/Service.php(298): DreamFactory\Core\Models\Service::storedContentToArray('swagger: '2.0'\n...', 1)
#1 /opt/dreamfactory/vendor/dreamfactory/df-core/src/Services/Swagger.php(120): DreamFactory\Core\Models\Service::getStoredContentForService(Object(DreamFactory\Core\Models\Service))
#2 /opt/dreamfactory/vendor/dreamfactory/df-core/src/Services/Swagger.php(76): DreamFactory\Core\Services\Swagger->getSwagger()
```

**Comment by leehicks** [comment]
Did the yaml in question pass validation in the [swagger editor](http://editor.swagger.io/#/)? If so, could you email me the yaml file. The previous ones you sent work so I am assuming this is a different file.

**Comment by leehicks** [comment]
This looks like a problem with the software setup (i.e. composer and/or autoloader). Any errors or problems after running composer update or install? Assuming this is after modifying a clean install with the bug fixes I sent you?

**Comment by philicious** [comment]
@leehicks `vendor/symfony/` on 2.2 and same on 2.2.1
```
drwxr-xr-x 30 www-data www-data 4096 Jul 12 17:07 console
drwxr-xr-x 10 www-data www-data 4096 Jul 12 17:07 debug
drwxr-xr-x 20 www-data www-data 4096 Jul 12 17:07 dependency-injection
drwxr-xr-x  8 www-data www-data 4096 Jul 12 17:07 event-dispatcher
drwxr-xr-x 10 www-data www-data 4096 Jul 12 17:07 finder
drwxr-xr-x  8 www-data www-data 4096 Jul 12 17:07 http-foundation
drwxr-xr-x 34 www-data www-data 4096 Jul 12 17:07 http-kernel
drwxr-xr-x  4 www-data www-data 4096 Jul 12 17:07 polyfill-mbstring
drwxr-xr-x  4 www-data www-data 4096 Jul 12 17:07 polyfill-php54
drwxr-xr-x  2 www-data www-data 4096 Jul 12 17:07 polyfill-php55
drwxr-xr-x  2 www-data www-data 4096 Jul 12 17:07 polyfill-php56
drwxr-xr-x  2 www-data www-data 4096 Jul 12 17:07 polyfill-util
drwxr-xr-x  8 www-data www-data 4096 Jul 12 17:07 process
drwxr-xr-x 14 www-data www-data 4096 Jul 12 17:07 routing
drwxr-xr-x 20 www-data www-data 4096 Jul 12 17:07 translation
drwxr-xr-x 16 www-data www-data 4096 Jul 12 17:07 var-dumper
```

**Comment by philicious** [comment]
@leehicks I added the require as per https://github.com/dreamfactorysoftware/df-core/commit/c99b5db6449e87923b96a7af827cf3c2878644a0 and run `compsoer update` , and the error is gone
